name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        python3 grep.py > /tmp/changelog.txt
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit --file /tmp/changelog.txt || exit 0
        git push